SELECT IL.NAME, I.SUMMARY, I.DESCRIPTION
FROM ISSUES I JOIN ISSUESLISTS IL ON I.USER_ID_ASSIGNEDTO = IL.ID;

SELECT U.FIRSTNAME, U.LASTNAME, I.SUMMARY
FROM ISSUES I JOIN USERS U ON U.ID = I.USER_ID_ASSIGNEDTO;

SELECT U.FIRSTNAME, U.LASTNAME, COUNT(*) TASK_NUMBER
FROM ISSUES I JOIN USERS U ON U.ID = I.USER_ID_ASSIGNEDTO
GROUP BY USER_ID_ASSIGNEDTO;